### ISSUE TITLE
Run oslom inside a script

### ISSUE THREAD

**Issue by LenaBencina** [hhromic/python-oslom-runner#2]
Hi,

is it possible to get an example how to run Oslom via python script? I am doing a stability analysis of community detection algorithms and I would like to include it in my code.

Thanks.

Best,
Lena

**Comment by hhromic** [comment]
Hi, thanks for using oslom runner!
Sorry to not document how to use the runner programatically, however it is very straight-forward. You can check the main `oslom/runner.py` module, where you will find two main functions to run Oslom: `run` and `run_in_memory`. They both use the same arguments.

The difference is that the in-memory version doesn't require the data to be stored in files and returns the results via Python. This function automatically creates a temporary file before calling oslom.

To use any of these functions, you just need to create a `Namespace` object for the arguments and populate it according to the command line arguments. Afterwards, you can call the oslom runner functions. For example:
```python
from argparse import Namespace
import oslom

# run oslom with files already on disk
args = Namespace()
args.edges = "input_file.tsv"
args.output_clusters = "output_file.json"
args.min_cluster_size = 3
args.oslom_output = "oslom_output"  # directory for oslom aux output files, if needed
args.oslom_exec = "oslom_undir"  # if you want the undirected graph version
oslom.run(args)

# run oslom with in-memory data
args = Namespace()
args.min_cluster_size = 3
args.oslom_output = "oslom_output"  # directory for oslom aux output files, if needed
args.oslom_exec = "oslom_undir"  # if you want the undirected graph version

# edges is an iterable of tuples (source, target, weight)
# source, target and weight must be integers 0 <= n <= 2^32 - 1
edges = [(0, 1, 1.0), (1, 2, 1), (2, 0, 1)]
clusters = oslom.run_in_memory(args, edges)
print(clusters)
```

Hope this sheds some light and I hope to update the documentation soon with all this information. Thanks again for using and let me know if you need more help.

**Comment by hhromic** [comment]
Sorry, just recalled that the source and target nodes in the edges don't need to be integers at all, they can be any string and will be automatically translated to integers for oslom. However, the number of distinct node ids must still not be > 2^32-1.

**Comment by LenaBencina** [comment]
Hi,
thank you for the example. However I still have some troubles running it. 

Trying to run it via run_in_memory without oslom_output and oslom_exec produces an error AttributeError: 'Namespace' object has no attribute 'oslom_exec'. I tried to run it with oslom_output and oslom_exec anyway and I get AttributeError: 'Namespace' object has no attribute 'oslom_args'. I am looking at the code but somehow I don't get it. :)

**Comment by hhromic** [comment]
Hi again. Sorry for the confusion, I haven't used this module since a long time. I took a re-read of the code now and indeed I made some mistakes on my example. This is a working example now:
```
from argparse import Namespace
import oslom
from oslom.runner import DEF_OSLOM_EXEC, DEF_OSLOM_ARGS

# run oslom with files already on disk
args = Namespace()
args.edges = "/path/to/input_edges.tsv"
args.output_clusters = "/path/to/output_clusters.json"
args.min_cluster_size = 3
args.oslom_output = "/path/to/oslom_aux_files"
args.oslom_exec = DEF_OSLOM_EXEC
args.oslom_args = DEF_OSLOM_ARGS
oslom.run(args)

# run oslom with in-memory data
args = Namespace()
args.min_cluster_size = 0
args.oslom_exec = DEF_OSLOM_EXEC
args.oslom_args = DEF_OSLOM_ARGS

# edges is an iterable of tuples (source, target, weight)
# source, target and weight must be integers 0 <= n <= 2^32 - 1
edges = [(0, 1, 1.0), (1, 2, 1), (2, 0, 1)]
clusters = oslom.run_in_memory(args, edges)
print(clusters)
```
This uses the default arguments for oslom: `DEF_OSLOM_ARGS = ["-w", "-r", "10", "-hr", "10"]`. If you want to customise them, just create a new list with the extra parameters. You must not pass the `-f` parameter to this list as the runner takes care of it.
Also, the directed version of oslom is used as default: `DEF_OSLOM_EXEC = "oslom_dir"`. If want to use the undirected version of oslom, just use `oslom_undir` instead.
The auxiliary files directory `args.oslom_output` is mandatory for the `run` function and is not required for the `run_in_memory` function.

Hope this works for you now!

**Comment by hhromic** [comment]
Hi again,
I now updated the package to include easier access to the default values constants in the module and added instructions for programmatic usage. You should update your package locally (`pip install oslom-runner`).

Please re-read the main README file for the definitive example: <https://github.com/hhromic/python-oslom-runner/blob/master/README.md>

Let me know if you could make it work with these instructions. Thanks!

**Comment by LenaBencina** [comment]
Still getting an error with in-memory run: FileNotFoundError: [Errno 2] No such file or directory: 'oslom_dir': 'oslom_dir'.  It seems like DEF_OSLOM_EXEC should be a directory? I am a bit confused.. :)

**Comment by LenaBencina** [comment]
Sorry didn't see your comment, I will try and let you know. Thanks!

**Comment by hhromic** [comment]
No, `oslom_exec` is the path to the OSLOM executable. That error means that you don't have the OSLOM binaries installed on your system. You must install them first from: <http://oslom.org/software.htm>

For easier usage, make sure the compiled binary is put in your environment's PATH variable. If you don't do this, then you must give the full path to the executable in `args.oslom_exec`.

This runner is a wrapper on top of OSLOM to make it easier to work with, it doesn't come with OSLOM.

**Comment by LenaBencina** [comment]
It's working now. Thank you for your help.

**Comment by LenaBencina** [comment]
Just one more question - is there a random seed that I can set to get reproducible results?
Thanks!

**Comment by hhromic** [comment]
Hi, yes you can use a fixed random seed for reproducible results. For this, you can use the `-seed m` OSLOM option (see [the documentation](http://www.oslom.org/code/ReadMe.pdf)).

> 3. -seed m. The program is not deterministic, so it needs a seed for its random number
generator. Using this option it will be set equal to m, otherwise the seed will be set
reading the file time_seed.dat, which will be updated afterwards.

A way to use it with the runner is by appending it to the `args.oslom_args` list like this:
```python
from argparse import Namespace
import oslom

# run OSLOM with data in Python objects
args = Namespace()
args.min_cluster_size = 0
args.oslom_exec = oslom.DEF_OSLOM_EXEC
args.oslom_args = oslom.DEF_OSLOM_ARGS + ["-seed", "12345678"]

# edges is an iterable of tuples (source, target, weight)
# in the same format as the command-line version
edges = [(0, 1, 1.0), (1, 2, 1), (2, 0, 1)]
clusters = oslom.run_in_memory(args, edges)
print(clusters)
```
